language: php
php:
  - 5.3
env:
  - MAGENTO_VERSION=magento-ce-1.9.1.0
script:
  - curl -sSL https://raw.githubusercontent.com/webguys-de/MageTestStand/master/setup.sh | bash
addons:
  code_climate:
    repo_token: 03942e903cbb5b61f64625e1e18d98949cd802db4d4e422858ed5ac98e995afc
notifications:
  email:
    recipients:
      - dev@mkleine.de
    on_success: always
    on_failure: always
